use_nerdfont = true
repeat = "playlist"
flip_status_indicators = true
library_tabs = ["playlists","tracks","albums","artists"]

[theme]
background = "black"
primary = "#d5c4a1"
secondary = "#d5c4a1"
title = "green"
playing = "green"
playing_selected = "light green"
playing_bg = "black"
highlight = "black"
highlight_bg = "light black"
error = "#d5c4a1"
error_bg = "red"
statusbar = "black"
statusbar_progress = "green"
statusbar_bg = "green"
cmdline = "#d5c4a1"
cmdline_bg = "black"
search_match = "light green"

[keybindings]
"Esc" = "back"
"h" = "back"
"Ctrl+w" = "save queue"
"Ctrl+j" = "previous"
"Ctrl+k" = "next"
"Alt+j" = "move left 1"
"Alt+k" = "move right 1"
"Ctrl+d" = "move down 5"
"Ctrl+u" = "move up 5"
"Ctrl+f" = "move down 10"
"Ctrl+b" = "move up 10"
"g" = "move bottom"
"G" = "move top"
"Shift+j" = "shift down 1"
"Shift+k" = "shift up 1"
"Shift+u" = "seek +5000"
"Shift+d" = "seek -5000"
"Shift+l" = "open current"
"l" = "open selected"
"Space" = "playpause"
"i" = "insert"
"Shift+y" = "share current"
"y" = "share selected"
"\"" = "queue"

"<" = "noop"
">" = "noop"
"Ctrl+a" = "noop"
"Ctrl+e" = "noop"
"Ctrl+l" = "noop"
"Ctrl+n" = "noop"
"Ctrl+p" = "noop"
"Ctrl+s" = "noop"
"Ctrl+v" = "noop"
"Down" = "noop"
"End" = "noop"
"Home" = "noop"
"Shift+o" = "noop"
"o" = "noop"
"Left" = "noop"
"PageDown" = "noop"
"PageUp" = "noop"
"Right" = "noop"
"Shift+Down" = "noop"
"Shift+Up" = "noop"
"Shift+p" = "noop"
"Shift+x" = "noop"
"Up" = "noop"
"x" = "noop"
